server {
    listen 80;
    server_name webdesign.thesysm.com;
    include proxy_params;
    include /etc/nginx/snippets/common_django_app.conf;

    location / {
        proxy_pass http://unix:/run/gunicorn_webdesign.sock;
    }

    location /static/ {
        alias /home/cskang/ganzskang/WebDesignStyle12/staticfiles/;
        access_log off;
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
        try_files $uri =404;
    }

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location = /robots.txt {
        log_not_found off;
        access_log off;
    }
}
