from django.utils.translation import gettext_lazy as _


def site(name, url, intro):
    return {
        "name": name,
        "url": url,
        "intro": intro,
    }


STYLE_DATA = [
    {
        "slug": "minimalism",
        "name": _("Minimalism"),
        "subtitle": _("Quiet spacing, restrained color, and decisive hierarchy."),
        "thumbnail_image": "images/styles/minimalism-thumb.svg",
        "hero_image": "images/styles/minimalism-hero.svg",
        "keywords": [_("Calm"), _("Editorial"), _("Whitespace")],
        "definition": _("Minimalism removes decorative noise so layout, typography, and spacing carry the experience. It depends on precision rather than abundance."),
        "key_visual_cues": [
            _("Large margins and deliberate negative space."),
            _("One or two typefaces with strong scale contrast."),
            _("A tight neutral palette with a single accent color."),
        ],
        "good_for": [
            _("Premium brands and portfolio sites."),
            _("Products with strong photography or a focused value proposition."),
            _("Landing pages that need fast visual comprehension."),
        ],
        "watch_outs": [
            _("Too little contrast can make the interface feel unfinished."),
            _("Sparse layouts fail when the content hierarchy is unclear."),
            _("Weak imagery is exposed immediately."),
        ],
        "quick_recipe": _("Use a warm off-white background, one serif or grotesk pairing, a single accent, and let spacing do most of the work."),
        "representative_sites": [
            site("Nendo", "https://www.nendo.jp/en/", _("An especially strict minimal portfolio: sparse navigation, monochrome restraint, and generous empty space keep attention on the work itself.")),
            site("Toteme", "https://toteme.com/", _("Luxury ecommerce with disciplined typography, calm negative space, and product imagery given room to breathe.")),
            site("Kinfolk", "https://www.kinfolk.com/", _("Editorial minimalism built from soft tone, light composition, and a highly controlled visual tempo.")),
        ],
    },
    {
        "slug": "neo-brutalism",
        "name": _("Neo-Brutalism"),
        "subtitle": _("Bold blocks, thick borders, and unapologetic contrast."),
        "thumbnail_image": "images/styles/neo-brutalism-thumb.svg",
        "hero_image": "images/styles/neo-brutalism-hero.svg",
        "keywords": [_("Bold"), _("Raw"), _("Graphic")],
        "definition": _("Neo-Brutalism embraces hard edges, obvious structure, and an intentionally blunt visual language that feels direct and youthful."),
        "key_visual_cues": [
            _("Heavy black outlines and offset shadows."),
            _("High-contrast primaries or punchy candy colors."),
            _("Chunky buttons and playful, almost poster-like composition."),
        ],
        "good_for": [
            _("Creative tools and startup launches."),
            _("Campaign microsites that need a memorable first impression."),
            _("Brands that want to feel outspoken and internet-native."),
        ],
        "watch_outs": [
            _("Overuse can feel noisy or gimmicky."),
            _("Thick borders everywhere reduce hierarchy."),
            _("Accessibility suffers if color and type choices are careless."),
        ],
        "quick_recipe": _("Pair a bright background with black outlines, oversized labels, sticker-like cards, and drop shadows that look intentionally physical."),
        "representative_sites": [
            site("Yale School of Art", "https://www.art.yale.edu/", _("Still one of the clearest references for anti-polished web aesthetics: loud color, raw structure, and deliberate refusal of conventional refinement.")),
            site("MSCHF", "https://mschf.com/", _("Aggressive numbering, sparse raw typography, and anti-design presentation push the site into a strong contemporary brutalist attitude.")),
            site("Buffalo Wild Wings", "https://www.buffalowildwings.com/", _("Poster-like yellow-black contrast, oversized headlines, and heavy visual blocks make the brand feel loud and blunt in a neo-brutalist way.")),
        ],
    },
    {
        "slug": "glassmorphism",
        "name": _("Glassmorphism"),
        "subtitle": _("Translucent layers floating over luminous backgrounds."),
        "thumbnail_image": "images/styles/glassmorphism-thumb.svg",
        "hero_image": "images/styles/glassmorphism-hero.svg",
        "keywords": [_("Frosted"), _("Layered"), _("Luminous")],
        "definition": _("Glassmorphism uses blurred, semi-transparent surfaces to create depth, softness, and a polished operating-system feel."),
        "key_visual_cues": [
            _("Frosted panels with blur and translucent fills."),
            _("Soft highlights, thin borders, and layered glow."),
            _("Gradients or color clouds behind the glass."),
        ],
        "good_for": [
            _("Concept demos and premium dashboards."),
            _("Interfaces that benefit from a sense of depth."),
            _("Brands aiming for a polished, futuristic tone."),
        ],
        "watch_outs": [
            _("Too much blur kills readability."),
            _("Without a strong background, the effect looks flat."),
            _("Performance can suffer if effects are overused."),
        ],
        "quick_recipe": _("Start with an aurora background, place translucent cards above it, then add subtle blur, faint borders, and restrained glow."),
        "representative_sites": [
            site("Glass UI", "https://ui.glass/", _("A direct style reference built around frosted cards, layered transparency, and luminous backgrounds rather than generic marketing visuals.")),
            site("Liquid Glass UI", "https://www.liquidglassui.net/", _("A modern gallery of liquid-glass patterns that makes blur, translucency, and floating depth easy to compare at a glance.")),
            site("CSS Glass", "https://css.glass/", _("A glassmorphism generator whose entire interface revolves around translucent panels and blur-heavy card treatment.")),
        ],
    },
    {
        "slug": "neumorphism",
        "name": _("Neumorphism"),
        "subtitle": _("Soft extrusions and gentle depth from light and shadow."),
        "thumbnail_image": "images/styles/neumorphism-thumb.svg",
        "hero_image": "images/styles/neumorphism-hero.svg",
        "keywords": [_("Soft"), _("Tactile"), _("Embossed")],
        "definition": _("Neumorphism simulates surfaces pressed into or raised out of the background with subtle shadows rather than obvious borders."),
        "key_visual_cues": [
            _("Monochrome surfaces with soft dual shadows."),
            _("Rounded geometry and low-contrast edges."),
            _("Controls that look pressed, inset, or pillowy."),
        ],
        "good_for": [
            _("Ambient utility interfaces and concept pieces."),
            _("Music controls, calculators, and compact widgets."),
            _("Visual experiments centered on softness."),
        ],
        "watch_outs": [
            _("Low contrast often hurts accessibility."),
            _("Dense information layouts lose clarity quickly."),
            _("The style can feel dated if applied indiscriminately."),
        ],
        "quick_recipe": _("Use one base surface color, then create depth only through paired light and dark shadows with generous corner radius."),
        "representative_sites": [
            site("Neumorphism.io", "https://neumorphism.io/", _("One of the cleanest pure references for soft raised and inset surfaces, focused almost entirely on the core visual effect.")),
            site("Neumorphism UI", "https://themewagon.github.io/neumorphism-ui/", _("A full kit demo that applies the style across cards, forms, alerts, and panels, making the depth system easy to study.")),
            site("Momentum Dash", "https://momentumdash.com/", _("Not purely neumorphic, but its soft panels, rounded controls, and gentle depth cues make it a useful real-product reference.")),
        ],
    },
    {
        "slug": "swiss-typographic",
        "name": _("Swiss / Typographic"),
        "subtitle": _("Grids, order, and typography as the main image."),
        "thumbnail_image": "images/styles/swiss-typographic-thumb.svg",
        "hero_image": "images/styles/swiss-typographic-hero.svg",
        "keywords": [_("Grid"), _("Type"), _("Structure")],
        "definition": _("Swiss style prioritizes clarity through disciplined grids, strong alignment, and typography-led composition with almost architectural restraint."),
        "key_visual_cues": [
            _("Visible grid logic and left-aligned type."),
            _("Sans-serif typography with strong scale and rhythm."),
            _("Sparse, intentional use of color and rules."),
        ],
        "good_for": [
            _("Cultural institutions and editorial products."),
            _("B2B sites that need instant structure and trust."),
            _("Landing pages with strong copywriting."),
        ],
        "watch_outs": [
            _("Rigid composition can feel cold without warmth elsewhere."),
            _("Poor copy becomes very obvious."),
            _("Breaking the grid carelessly weakens the style."),
        ],
        "quick_recipe": _("Build on a strict column grid, keep alignment disciplined, choose one neutral sans, and let scale and spacing create drama."),
        "representative_sites": [
            site("Swiss Typefaces", "https://www.swisstypefaces.com/", _("A strong living example of grid-based layout, flush-left structure, and typography doing most of the visual work.")),
            site("Swiss Typography Microsite", "https://swiss-typography.webflow.io/", _("An explicit educational demo of Swiss alignment, hierarchy, and restrained color, useful when learning the style visually.")),
            site("Rosmarie Tissi", "https://rosmarie-tissi.ch/", _("A site connected to a major Swiss designer whose work makes typographic structure and compositional rigor easy to trace.")),
        ],
    },
    {
        "slug": "playful-illustration",
        "name": _("Playful Illustration"),
        "subtitle": _("Expressive shapes, characters, and friendly motion cues."),
        "thumbnail_image": "images/styles/playful-illustration-thumb.svg",
        "hero_image": "images/styles/playful-illustration-hero.svg",
        "keywords": [_("Friendly"), _("Illustrated"), _("Expressive")],
        "definition": _("Playful Illustration uses drawn elements, cheerful palettes, and animated composition to make digital products feel human and approachable."),
        "key_visual_cues": [
            _("Custom illustrations, blobs, and stickers."),
            _("Rounded type or soft geometric layout blocks."),
            _("Bright palettes with a sense of movement."),
        ],
        "good_for": [
            _("Education, wellness, and kid-friendly products."),
            _("Brand storytelling and onboarding pages."),
            _("Services that need emotional warmth."),
        ],
        "watch_outs": [
            _("Too many illustration styles create inconsistency."),
            _("Excess whimsy can undercut credibility."),
            _("Busy scenes can distract from calls to action."),
        ],
        "quick_recipe": _("Anchor the page with a friendly illustration style, use rounded cards, keep copy short, and support the mood with buoyant color."),
        "representative_sites": [
            site("Duolingo", "https://www.duolingo.com/", _("Mascot-led product storytelling, bold color, and unmistakable character work make it one of the strongest playful references online.")),
            site("Mailchimp", "https://mailchimp.com/", _("Combines illustration, brand personality, and friendly marketing language to soften a fairly technical product category.")),
            site("Headspace", "https://www.headspace.com/", _("Uses soft characters and approachable visual language to keep the product calm, warm, and emotionally legible.")),
        ],
    },
    {
        "slug": "dark-tech-saas",
        "name": _("Dark Tech / SaaS"),
        "subtitle": _("High-contrast product marketing with a futuristic edge."),
        "thumbnail_image": "images/styles/dark-tech-saas-thumb.svg",
        "hero_image": "images/styles/dark-tech-saas-hero.svg",
        "keywords": [_("Dark"), _("Product"), _("Futuristic")],
        "definition": _("Dark Tech / SaaS combines dark surfaces, data-like graphics, and glow accents to frame software as advanced, fast, and credible."),
        "key_visual_cues": [
            _("Near-black backgrounds with cool neon accents."),
            _("Code-like UI panels, charts, and product frames."),
            _("Sharp type, gradients, and controlled glow."),
        ],
        "good_for": [
            _("Developer tools and AI products."),
            _("Security, infrastructure, and analytics companies."),
            _("Product launch pages that need technical authority."),
        ],
        "watch_outs": [
            _("Without hierarchy, dark layouts become muddy."),
            _("Glow everywhere reduces readability."),
            _("Generic product mockups can feel interchangeable."),
        ],
        "quick_recipe": _("Use graphite and midnight tones, highlight with cyan or lime, then frame screenshots inside clean product windows with crisp labels."),
        "representative_sites": [
            site("Vercel", "https://vercel.com/", _("A benchmark dark-tech marketing site: near-black surface, sharp product framing, and restrained but polished glow treatment.")),
            site("Supabase", "https://supabase.com/", _("Combines code-adjacent visuals, dark surfaces, and crisp green accents in a way that feels deeply native to developer SaaS.")),
            site("Resend", "https://resend.com/", _("High-contrast, developer-first presentation with dark UI windows and technical clarity instead of generic startup gloss.")),
        ],
    },
    {
        "slug": "gradient-aurora",
        "name": _("Gradient / Aurora"),
        "subtitle": _("Atmospheric blends and color fields that feel alive."),
        "thumbnail_image": "images/styles/gradient-aurora-thumb.svg",
        "hero_image": "images/styles/gradient-aurora-hero.svg",
        "keywords": [_("Gradient"), _("Atmospheric"), _("Glow")],
        "definition": _("Gradient / Aurora style relies on smooth chromatic blends and soft light to create emotional depth without heavy illustration or texture."),
        "key_visual_cues": [
            _("Large blurred gradients and subtle movement."),
            _("Minimal foreground UI over luminous fields."),
            _("Color transitions that imply depth and mood."),
        ],
        "good_for": [
            _("Creative agencies and modern launch pages."),
            _("Brands selling inspiration, media, or future-facing products."),
            _("Sites that need immediate visual atmosphere."),
        ],
        "watch_outs": [
            _("Weak contrast can make content disappear."),
            _("Too many gradients create visual soup."),
            _("The style needs disciplined typography to stay premium."),
        ],
        "quick_recipe": _("Blend two or three high-saturation colors, blur them generously, then overlay very clear type and restrained interface chrome."),
        "representative_sites": [
            site("Linear", "https://linear.app/", _("A premium product site where glow-backed gradients and atmospheric color fields are central to the brand’s visual identity.")),
            site("Framer", "https://www.framer.com/", _("Uses richly lit gradients, soft luminous backgrounds, and motion to create a future-facing aurora mood around the product.")),
            site("Aurora Gradient Generator", "https://auroragradient.com/", _("A direct reference site for the style itself, useful because its whole product is built around aurora-like blended backgrounds.")),
        ],
    },
    {
        "slug": "bento-ui",
        "name": _("Bento UI"),
        "subtitle": _("Modular cards arranged like a curated product tray."),
        "thumbnail_image": "images/styles/bento-ui-thumb.svg",
        "hero_image": "images/styles/bento-ui-hero.svg",
        "keywords": [_("Modular"), _("Cards"), _("Product")],
        "definition": _("Bento UI organizes information into distinct but harmonious tiles, making complex products feel scannable and feature-rich."),
        "key_visual_cues": [
            _("Uneven card sizes inside a balanced grid."),
            _("Clear product snippets, stats, and small visuals."),
            _("Rounded containers with generous internal spacing."),
        ],
        "good_for": [
            _("Product marketing and feature showcases."),
            _("AI tools, mobile apps, and software homepages."),
            _("Any site with many concise selling points."),
        ],
        "watch_outs": [
            _("Without hierarchy, every tile competes equally."),
            _("The layout becomes cluttered if cards are overfilled."),
            _("Spacing discipline is essential."),
        ],
        "quick_recipe": _("Compose a mixed-size card grid, vary the content density per tile, and use one unified radius, shadow, and spacing system."),
        "representative_sites": [
            site("Notion", "https://www.notion.com/", _("Its homepage explicitly uses bento-like product tiles and mixed-size modules to explain many features without becoming a wall of text.")),
            site("BentoAnimation", "https://www.bentoanimation.com/", _("A specialized site built around bento-first dark card layouts, useful as a highly legible example of the style in isolation.")),
            site("Aceternity UI Feature Sections", "https://ui.aceternity.com/feature-section", _("An explicit component gallery for bento layouts, useful for studying card hierarchy, asymmetry, and modular feature presentation.")),
        ],
    },
    {
        "slug": "editorial-magazine",
        "name": _("Editorial / Magazine"),
        "subtitle": _("Narrative layouts that borrow from print publishing."),
        "thumbnail_image": "images/styles/editorial-magazine-thumb.svg",
        "hero_image": "images/styles/editorial-magazine-hero.svg",
        "keywords": [_("Narrative"), _("Print"), _("Sophisticated")],
        "definition": _("Editorial / Magazine style uses dramatic type, strong image crops, and reading rhythm to create a curated storytelling experience."),
        "key_visual_cues": [
            _("Large serif headlines and asymmetric composition."),
            _("Photography-led sections with captions and side notes."),
            _("A page flow that feels paced rather than purely utilitarian."),
        ],
        "good_for": [
            _("Fashion, culture, and premium brand storytelling."),
            _("Founder stories, journals, and campaign pages."),
            _("Sites where tone matters as much as utility."),
        ],
        "watch_outs": [
            _("Long-form layouts need careful responsive handling."),
            _("Bad typography choices undermine the whole approach."),
            _("Too much ornament can slow scanning."),
        ],
        "quick_recipe": _("Lead with a striking serif headline, use confident image crops, and alternate dense text moments with breathing space."),
        "representative_sites": [
            site("Kinfolk", "https://www.kinfolk.com/", _("A calm but unmistakably editorial site where image pacing, typography, and rhythm feel inherited from print publishing.")),
            site("AnOther Magazine", "https://www.anothermag.com/", _("A fashion and culture publication with strong headline treatment, image-led flow, and clearly magazine-born layout instincts.")),
            site("Aesop", "https://www.aesop.com/", _("Not a magazine, but an excellent commerce-meets-editorial reference thanks to its typography, reading rhythm, and art-directed pacing.")),
        ],
    },
    {
        "slug": "retro-y2k",
        "name": _("Retro / Y2K"),
        "subtitle": _("Chrome shine, nostalgic curves, and internet-era energy."),
        "thumbnail_image": "images/styles/retro-y2k-thumb.svg",
        "hero_image": "images/styles/retro-y2k-hero.svg",
        "keywords": [_("Nostalgic"), _("Chrome"), _("Energetic")],
        "definition": _("Retro / Y2K revives late-90s and early-2000s web aesthetics through metallic highlights, glossy surfaces, and playful digital nostalgia."),
        "key_visual_cues": [
            _("Iridescent gradients, chrome text, and shiny pills."),
            _("Rounded windows, stars, and layered stickers."),
            _("High-energy color with a pop-culture tone."),
        ],
        "good_for": [
            _("Fashion, music, and youth-oriented campaigns."),
            _("Brands leaning into nostalgia or internet culture."),
            _("Microsites that need strong personality fast."),
        ],
        "watch_outs": [
            _("It can drift into parody quickly."),
            _("Too many effects lower perceived quality."),
            _("Content still needs clear modern hierarchy."),
        ],
        "quick_recipe": _("Mix chrome gradients with bubble-like UI, add sparkle details sparingly, and keep the layout controlled so the nostalgia reads intentional."),
        "representative_sites": [
            site("Rice2k", "https://rice2k.neocities.org/image-gallery", _("An explicit archive of retro web graphics, blinkies, and nostalgic ornament that captures Y2K internet culture directly.")),
            site("Superbad", "https://superbad.com/", _("A historic anti-clean web-art site whose ASCII, raw HTML, and chaotic digital energy still feel deeply tied to early-2000s internet aesthetics.")),
            site("Y2K Shop", "https://y2k-shop.com/", _("A more commercial example where nostalgic chrome-pop energy and 2000s visual references are used overtly as the brand language.")),
        ],
    },
    {
        "slug": "material-system-ui",
        "name": _("Material / System UI"),
        "subtitle": _("Polished components, clear states, and dependable rhythm."),
        "thumbnail_image": "images/styles/material-system-ui-thumb.svg",
        "hero_image": "images/styles/material-system-ui-hero.svg",
        "keywords": [_("System"), _("Clear"), _("Scalable")],
        "definition": _("Material / System UI emphasizes consistency, accessible structure, and component logic so interfaces feel immediately legible and scalable."),
        "key_visual_cues": [
            _("Component-driven layout with clear states."),
            _("Layered surfaces, subtle elevation, and consistent spacing."),
            _("Practical typography and icon-supported interaction."),
        ],
        "good_for": [
            _("Product ecosystems and utility-focused interfaces."),
            _("Design systems and internal tools."),
            _("Teams that need a stable visual foundation."),
        ],
        "watch_outs": [
            _("Generic execution can feel anonymous."),
            _("Too much component uniformity reduces personality."),
            _("Elevation and spacing need consistency to work."),
        ],
        "quick_recipe": _("Use a clear spacing scale, reliable component states, a practical sans, and one accent color to add identity without breaking order."),
        "representative_sites": [
            site("Material 3", "https://m3.material.io/", _("The canonical reference for material design logic, showing the system’s component behavior, hierarchy, and layout philosophy directly.")),
            site("Google Workspace", "https://workspace.google.com/", _("A large-scale Google product surface with system-driven cards, iconography, spacing, and clearly structured feature modules.")),
            site("Google Store", "https://store.google.com/", _("A commerce-facing example of clean modular sections and dependable UI rhythm with a distinctly system-led feel.")),
        ],
    },
]

STYLE_LOOKUP = {style["slug"]: style for style in STYLE_DATA}
